apiVersion: v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  source:                       
    git:
      uri: https://github.com/noelo/customjenkins
    type: Git
  strategy:                     
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins-2-rhel7:latest
    type: Source
  output:                       
    to:
      kind: ImageStreamTag
      name: custom-jenkins:latest
